<?php

/**
* @file
* Permite a los usuarios añadir anotaciones privadas a nodos
* 
* Añade un campo de texto al mostrar un nodo
* para que los usuarios autenticados puedan añadir notas
*/

/**
* Implementación de hook_menu().
*/
function annotate_menu() {
	$items['admin/config/annotate'] = array(
		'title' => 'Node annotation',
		'description' => 'Adjust node annotation option.',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
		);
	
	$items['admin/config/annotate/settings'] = array(
		'title' => 'Annotation settings',
		'description' => 'Change how annotations behave.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('annotate_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'annotate.admin.inc',
		);
		
		return $items;
}

/**
* Implementa hook_node_load()
**/

function annotate_node_load($nodes, $types){
	global $user;
	
	//Comprobar si la persona que ve el nodo es el auto, en caso contrario ocultar la anotación
	foreach($nodes as $node) {
		if($user->uid != $node->uid){
			unset($node->annotation);
		}
	}
}